from typing import List
import wx
import MyUI

class Console(wx.Frame):
    def __init__(self, *args, **kwargs):
        self.text_display: TextDisplay = ...
        self.console_sizer: wx.GridBagSizer = ...
        self.output_button: MyUI.MyButton = ...
        self.clear_button: MyUI.MyButton = ...
        ...
        
    def Clear_Button(self, *args) -> None:
        ...
    
    def Output_Button(self, *args) -> None:
        ...
        
    def Add_Text(self, text:str) -> None:
        ...
        
        
        
        
        
class TextDisplay(wx.Panel):
    def __init__(self, *args, **kwargs):
        self.text_output: List[wx.StaticText] = ...
        self.sizer: wx.BoxSizer = ...
        ...
        
    def AddText(self, text:str) -> None:
        ...
        
    def Clear(self) -> None:
        ...
        